spring:
  datasource:
    url: jdbc:h2:file:~/chatdb  # "testdb" — имя БД в памяти
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true  # Включает консоль H2
      path: /h2-console  # URL для доступа к консоли
  jpa:
    hibernate:
      ddl-auto: update  # Автоматическое создание таблиц
    show-sql: true      # Показывать SQL-запросы в логах
server:
  port: 8082
jwt:
  secret: Y2N8f8z1MPrxvRmfhg9i6LgrNuBxZl8MwVpFXuRvKUI=
  accessTokenExpirationMs: 3600000 # 1 час
  refreshTokenExpirationMs: 86400000 # 1 день
gpt:
  name: ${GPT_NAME:yandex}
  yandex:
    api-url: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
    gpt-model: yandexgpt
    folder-id: b1g4j51ocjsr8ir3hdlf
    key: ${YANDEX_API_KEY:#{null}}