spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.JsonSerializer
  datasource:
    url: jdbc:h2:file:~/chatdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 8082
jwt:
  secret: Y2N8f8z1MPrxvRmfhg9i6LgrNuBxZl8MwVpFXuRvKUI=
  accessTokenExpirationMs: 60000 # 1 минута
  refreshTokenExpirationMs: 86400000 # 1 день
gpt:
  name: ${GPT_NAME:yandex}
  yandex:
    api-url: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
    gpt-model: yandexgpt
    folder-id: b1g4j51ocjsr8ir3hdlf
    key: ${YANDEX_API_KEY:#{null}}
logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate.orm.jdbc.bind: OFF