name: chatServer CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Сборка jar-файла
        run: mvn clean package -DskipTests

      - name: Построить Docker-образ
        run: docker build -t chat-server-image -f Dockerfile .

      - name: Сохранить Docker-образ как tar
        run: docker save chat-server-image -o chat-server-image.tar

      - name: Загрузить Docker-образ как артефакт
        uses: actions/upload-artifact@v4
        with:
          name: chat-server-image
          path: chat-server-image.tar
